---
title: "Get Started"
author: "Maciej Nasinski"
output:
    rmarkdown::html_document:
        theme: "spacelab"
        highlight: "kate"
        toc: true
        toc_float: true
vignette: >
  %\VignetteIndexEntry{Get Started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Overview

Transparency and reproducibility are fundamental principles in data analysis across various fields, from academic
research to industry applications. The `ggcall` package enhances the functionality of `ggplot2` by enabling users to retrieve the complete code used to generate a `ggplot` object inside a function. This package is beneficial for understanding and replicating complex `ggplot2` plots returned by a function. From technical point of view, `ggcall` extends `ggplot2` `+` operator and `ggplot` function to track the history of plot construction.

`ggcall` makes a developer's life easier and limits the need to use base r metaprogramming or `rlang`.

`patchwork` ggplot2 related operators like `+`, `-`, `*`, `|`, `&` and `/` are optionally supported. 
`patchwork` is a package that expands the API to allow for arbitrarily complex composition of plots by, 
among others, providing mathematical operators for combining multiple plots.

An excellent implementation example is to create a bunch of ggplot templates, and we want them to be functions.
Then, each template will generate the expected plot, and the ggplot2 code behind is easy to get.

## Usage

Imagine using a package or function that generates a complex `ggplot2` visualization.  
Then, the ggplot code used to create the plot is not exposed.  
`ggcall` overcomes this barrier by extracting the hidden code, making it accessible for examination and modification. 

Here is a **simple** illustrative example with a scenario in which a function generates a `ggplot2` plot based on input data:

```r
remotes::install_github("https://github.com/Polkas/ggcall")
library(ggcall)

# Example: Create a function which combines a few ggplot layers
# Typically, it will be a function from your R package where you implemented ggcall
create_custom_plot <- function(data, x, y, bool = TRUE) {
  # layers have to be added with +
  gg <- ggplot(data, aes(x = .data[[x]], y = .data[[y]])) +
    geom_point(alpha = 0.4) +
    facet_grid(~gear)
    
  if (bool) {
    gg <- gg + theme(axis.title.x = element_blank())
  }

  func_internal <- function(gg) {
    gg + labs(title = "custom title")
  }

  func_internal(gg)
}

# gg_plot is a ggplot object
gg_plot <- create_custom_plot(mtcars, "wt", "mpg")
print(gg_plot)
# Retrieve the plot construction code
plot_call <- ggcall(gg_plot)
plot_call
# ggplot(data, aes(x = .data[[x]], y = .data[[y]])) + geom_point(alpha = 0.4) + 
#     facet_grid(~gear) + theme(axis.title.x = element_blank()) + 
#     labs(title = "custom title")
# attr(,"class")
# [1] "ggcall_code"
# attr(,"ggcall_env")
# <environment: abcd1234>

# Optionally: Style the code with styler
# install.packages("styler")
styler::style_text(
  paste(deparse(plot_call_with_assignments), collapse = "\n")
)

# Optionally: add assignments to call
plot_call_with_assignments <- ggcall_add_assignments(plot_call)
styler::style_text(
  paste(deparse(plot_call_with_assignments), collapse = "\n")
)

# Optionally: access call environment
# Access call environment and/or use it to evaluate the call
plot_call_env <- ggcall_env(plot_call)
as.list(plot_call_env)

# Optionally: reevaulate the call
# Reproduce the plot by evaluating the code
eval_ggcall(plot_call)
eval_ggcall(plot_call_with_assignments)

# Optionally overwrite variables
eval_ggcall(plot_call, mtcars = mtcars[1:10, ], x = "disp")
```

Here is an example with `patchwork` usage.

```r
remotes::install_github("https://github.com/Polkas/ggcall")
library(ggcall)
library(patchwork)

# Example: Create a function which combines a few ggplot layers
# Typically, it will be a function from your R package where you implemented ggcall
create_custom_plot <- function(data, x, y, bool = TRUE) {
  # layers have to be added with +
  gg <- ggplot(data, aes(x = .data[[x]], y = .data[[y]])) +
    geom_point(alpha = 0.4) +
    facet_grid(~gear)
    
  if (bool) {
    gg <- gg + theme(axis.title.x = element_blank())
  }

  func_internal <- function(gg) {
    gg + labs(title = "custom title")
  }

  # patchwork +
  func_internal(gg) + 
  # another ggplot added with patchwork
  ggplot(data, aes(x = .data[[x]], y = .data[[y]])) + 
  geom_point() + 
  theme(axis.title.y = element_blank(), axis.title.x = element_text(hjust = -0.15)) +
  plot_annotation(caption = "My Caption")
}

# gg_plot is a ggplot object
gg_plot <- create_custom_plot(mtcars, "wt", "mpg")
print(gg_plot)
# Retrieve the plot construction code
plot_call <- ggcall(gg_plot)
plot_call
# ggplot(data, aes(x = .data[[x]], y = .data[[y]])) + geom_point(alpha = 0.4) + 
#     facet_grid(~gear) + theme(axis.title.x = element_blank()) + 
#     labs(title = "custom title") + ggplot(data, aes(x = .data[[x]], 
#     y = .data[[y]])) + geom_point() + theme(axis.title.y = element_blank(), 
#     axis.title.x = element_text(hjust = -0.15)) + plot_annotation(caption = "My Caption")
# ...

# Optionally: Style the code with styler
# install.packages("styler")
styler::style_text(
  paste(deparse(plot_call), collapse = "\n")
)
# ggplot(data, aes(x = .data[[x]], y = .data[[y]])) +
#   geom_point(alpha = 0.4) +
#   facet_grid(~gear) +
#   theme(axis.title.x = element_blank()) +
#   labs(title = "custom title") +
#   ggplot(data, aes(x = .data[[x]], y = .data[[y]])) +
#   geom_point() +
#   theme(axis.title.y = element_blank(), axis.title.x = element_text(hjust = -0.15)) +
#   plot_annotation(caption = "My Caption")

# Optionally: add assignments to call
plot_call_with_assignments <- ggcall_add_assignments(plot_call)
styler::style_text(
  paste(deparse(plot_call_with_assignments), collapse = "\n")
)

# Optionally: access call environment
# Access call environment and/or use it to evaluate the call
plot_call_env <- ggcall_env(plot_call)
as.list(plot_call_env)

# Optionally: reevaulate the call
# Reproduce the plot by evaluating the code
eval_ggcall(plot_call)
eval_ggcall(plot_call_with_assignments)

# Optionally overwrite variables
eval_ggcall(plot_call, mtcars = mtcars[1:10, ], x = "disp")
```

## Developers Implementation

The ggcall can be implemented in a few ways to your package, direct dependency or standalone.


`usethis` package is optional but it truly simplify the process.
The `usethis` >= 2.2.0 is required to use `usethis::use_standalone`.

```
install.packages("usethis")
```

GENERAL COMMENTS:

```
# Apply only if needed
# In your own code remove all ggplot2:: prefix-ing before ggplot function calls
# ggplot2::ggplot(...) -> ggplot(...)
```

DIRECT DEPENDENCY:

An option is to use the ggcall as a DESCRIPTION file import dependency for your package.

```
usethis::use_package("ggcall")
```

```
# DO NOT import ggplot function from ggplot2 instead import it from ggcall

# a. When importing all ggplot2 functions
# #' @rawNamespace import(ggplot2, except = c(ggplot))
# #' @import ggcall
# b. When importing specific ggplot2 functions
# #' @importFrom ggplot2 geom_line
# #' @importFrom ggcall ggplot
```

STANALONE - copy paste the files to your own project:

with `patchwork` support

```
# copy paste the ggcall.R file to your own package R directory
# copy paste the patchwork.R file to your own package R directory
```

```r
usethis::use_package("ggplot2")
usethis::use_package("patchwork")
usethis::use_standalone("polkas/ggcall", "patchwork.R", ref = "v0.3.3")
# you may need to update the file time to time
```

without `patchwork` support

```
# copy paste the ggcall.R file to your own package R directory
```

```
usethis::use_package("ggplot2")
usethis::use_standalone("polkas/ggcall", "ggcall.R", ref = "v0.3.3")
# you may need to update the file time to time
```

### Example implementation in GGally package

A notable example of ggcall’s successful integration is seen in the `GGally` package fork.  
`GGally` package is a `ggplot2` extension used to create correlation matrices and scatterplot matrices.  
As `GGally` had already overwritten the `+.gg` operator to extend ggplot2’s functionality for their own reasons, demonstrating that overwriting operators can be considered an acceptable and practical solution.  

The `GGally` package required only minor changes to implement `ggcall`, showcasing how easily it can be integrated into existing solutions.   The copy and paste `ggcall` files to `GGally` are R/ggcall.R and OPTIONAL R/patchwork.R and the extended
already existing `+.gg` operator is located in R/ggpairs_add.R.

The `GGally` package fork with implemented `ggcall` is available on [Github](https://github.com/Polkas/ggally).  

Here is an illustrative example with the `GGally::ggcorr` function from the fork with `ggcall`:

```
remotes::install_github("https://github.com/Polkas/ggally")
library(GGally)

###########################
# Example for GGally ggcorr
###########################

data(mtcars)
gg <- GGally::ggcorr(
    mtcars,
    name = expression(rho),
    geom = "circle",
    max_size = 10,
    min_size = 2,
    size = 3,
    hjust = 0.75,
    nbreaks = 6,
    angle = -45,
    palette = "PuOr",
    legend.position = "top"
) + 
ggtitle("Correlation Matrix for mtcars Dataset")
# gg is a ggplot object
gg

# Retrieve the plot construction code
gg_call <- ggcall(gg)
gg_call

# Optionally: Style the code with styler
styler::style_text(deparse1(gg_call))

# Optionally: add assignments to call
gg_call_with_assignments <- ggcall_add_assignments(gg_call)
gg_call_with_assignments
styler::style_text(
  paste(deparse(gg_call_with_assignments), collapse = "\n")
)

# Optionally: reevaulate the call
# Reproduce the plot by evaluating the code
eval_ggcall(gg_call_with_assignments)
eval_ggcall(ggcall_add_assignments(gg_call))

##############################
# Example for GGally ggscatmat
##############################

data(iris)
gg <- GGally::ggscatmat(iris, color = "Species", columns = 1:4)
# gg is a ggplot object
gg

# Retrieve the plot construction code
gg_call <- ggcall(gg)
gg_call

# Optionally: Style the code with styler
styler::style_text(deparse1(gg_call))

# Optionally: add assignments to call
gg_call_with_assignments <- ggcall_add_assignments(gg_call)
gg_call_with_assignments
styler::style_text(
  paste(deparse(gg_call_with_assignments), collapse = "\n")
)

# Optionally: reevaulate the call
# Reproduce the plot by evaluating the code
eval_ggcall(gg_call)
eval_ggcall(gg_call_with_assignments)

##########################
# Example for GGally ggduo
##########################

# Not supported for ggmatrix like plots
# ggcall will fail as ggmatrix plots are not build with pure ggplot2

gg <- GGally::ggduo(tips, mapping = ggplot2::aes(colour = sex), columnsX = 3:4, columnsY = 1:2)
ggplot2::is.ggplot(gg)
# Fail gg_call <- ggcall(gg)
```

## Note

The solution is in the development and is expected not to work in specific situations.
