#' Enhanced `ggplot` Function with History Tracking
#'
#' Overrides the default `ggplot` function from the ggplot2 package, adding the
#' capability to track the history of plot construction. 
#' This function initializes a history attribute in the `ggplot` object.
#'
#' @param ... Arguments passed to the original ggplot function from ggplot2.
#'
#' @return A ggplot object of class 'ggplot_history', with an additional
#' attribute 'plot_history' that stores the history of plot construction.
#'
#' @seealso \code{\link[ggplot2]{ggplot}}
#' @importFrom ggplot2 ggplot
#' @examples
#' p <- ggplot(mtcars, aes(x=wt, y=mpg))
#' # the + function has to come from gghistory package
#' attr(p + geom_point(), "plot_history")
#'
#' @export
#'
ggplot <- function(...) {
  validate_ggplot()
  plot <- ggplot2::ggplot(...)

  # Initialize the history with the first call
  history <- list(match.call())
  attr(plot, "plot_history") <- history
  attr(plot, "plot_history_env") <- parent.frame()
  class(plot) <- c("ggplot_history", class(plot))

  plot
}

#' Custom '+' Operator for ggplot_history Objects
#'
#' Enhances the '+' operator for ggplot objects to track the history of
#' plot layers and modifications. This function is meant to be used in
#' conjunction with the enhanced ggplot function provided by this package.
#'
#' @param e1 A ggplot object of class 'ggplot_history'.
#' @param e2 A layer or theme to add to the ggplot object.
#'
#' @return A modified ggplot object with updated plot history.
#' @examples
#' p <- ggplot(mtcars, aes(x=wt, y=mpg)) + geom_point()
#' attr(p, "plot_history") # View the plot construction history
#'
#' @export
#'
`+.gg` <- function(e1, e2) {
  stopifnot(inherits(e1, "ggplot_history"))
  validate_ggplot()
  plot <- utils::getFromNamespace("+.gg", "ggplot2")(e1, e2)

  # Append to the existing history
  if (!is.null(attr(e1, "plot_history"))) {
    history <- attr(e1, "plot_history")
  } else {
    history <- list()
  }
  history <- c(history, list(substitute(e2)))
  attr(plot, "plot_history") <- history

  plot_env <- attr(plot, "plot_history_env")
  if (!identical(plot_env, parent.frame())) {
    attr(plot, "plot_history_env") <- merge_env(plot_env, parent.frame())
  }

  plot
}

#' Retrieve Plot Construction Code from ggplot_history Object
#'
#' Extracts the complete history of a ggplot object's construction,
#' providing a way to reproduce or inspect the plot. Designed to work
#' with ggplot objects of class 'ggplot_history'.
#'
#' @param plot A ggplot object of class 'ggplot_history'.
#' @param call `logical(1)` if `TRUE`, returns a callable expression
#' representing the plot construction.
#' If `FALSE`, returns a list of the history expressions.
#' By default `TRUE`
#'
#' @return Depending on the value of 'call', either a callable expression or
#' a list representing the history of the ggplot object.
#'
#' @examples
#' p <- ggplot(mtcars, aes(x=wt, y=mpg)) + geom_point()
#' plot_code <- get_ggplot_code(p)
#' print(plot_code)
#'
#' # eval(plot_code) # Reproduce the plot
#'
#' @export
#'
get_ggplot_code <- function(plot, call = TRUE) {
  stopifnot(inherits(plot, "ggplot_history"))
  history_attr <- attr(plot, "plot_history")
  if (call) {
    res <- Reduce(function(x, y) bquote(.(x) + .(y)), history_attr)
  } else {
    res <- history_attr
  }
  class(res) <- "ggplot_history_code"
  attr(res, "plot_history_env") <- attr(plot, "plot_history_env")
  res
}

#' Evaluate Plot Construction Code
#'
#' This function evaluates an expression representing a ggplot construction code.
#' It specifically uses the environment stored in the 'plot_history_env' attribute
#' of the expression, ensuring that the plot is reconstructed in the correct context.
#'
#' @param code An expression representing the ggplot construction code, typically
#'          generated by `get_ggplot_code`. This expression should have an
#'          attribute 'plot_history_env' that stores the environment in which
#'          the plot was originally created.
#'
#' @return The resulting ggplot object produced by evaluating the expression `x`.
#'
#' @examples
#' p <- ggplot(mtcars, aes(x=wt, y=mpg)) + geom_point()
#' plot_code <- get_ggplot_code(p)
#' reconstructed_plot <- eval_ggplot_code(plot_code)
#' print(reconstructed_plot)
#'
#' @export
#'
eval_ggplot_code <- function(code) {
  stopifnot(inherits(code, "ggplot_history_code"))
  validate_ggplot()
  eval(code, attr(code, "plot_history_env"))
}

#' @keywords internal
validate_ggplot <- function() {
  if (!requireNamespace("ggplot2")) {
    stop("ggplot2 package has to be installed.")
  }
}

#' @keywords internal
merge_env <- function(to_env, from_env) {
  stopifnot(is.environment(to_env), is.environment(from_env))
  for (name in ls(from_env)) {
    if (name %in% ls(to_env)) {
      warning(paste("Variable '", name, "' already exists in the target environment."))
    } else {
      assign(name, get(name, envir = from_env), envir = to_env)
    }
  }
  to_env
}
